### ISSUE TITLE
Deprecate some Twig extensions

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataIntlBundle#182]
The official twig extensions repository provides these filters: https://github.com/twigphp/Twig-extensions/blob/2c2a90088f34be0b35c5c80ea55704a602c4fdb4/lib/Twig/Extensions/Extension/Intl.php#L27-L29

I tested some of them:

```twig
<p>
    {{ 'now'|format_datetime(null, 'en') }}
    <br>
    {{ 'now'|format_datetime(null, 'fr') }}
</p>
<p>
    {{ 'now'|localizeddate('medium', 'medium', 'en') }}
    <br>
    {{ 'now'|localizeddate('medium', 'medium', 'fr') }}
</p>
```

The result is exactly the same.

I think we should consider deprecate the duplicate filter and use the official extensions instead.

One of the possible issue is the admin usage: https://sonata-project.org/bundles/intl/2-x/doc/reference/datetime.html#php-usage

But I think we can fallback to the official extension too. In case the extension is [not loaded](https://github.com/twigphp/Twig-extensions/issues/140#issuecomment-285592313), we may:

1. Raise an error telling the end user to activate the extension himself.
2. Load the twig extension from the concerned bundle (admin for the previous link). We should not load it from intl-bundle because it's not our role and we may load an unused extension.

I'll prefer option 1. Option 2 will be to "magical" for the end user IMHO.

Though?

**Comment by phansys** [comment]
Taking the date extension as example, even if we could emulate the basic behavior for these filters, I think is not possible to cover the complete features provided by them, since this bundle performs some additional operations to find the better suitable locale and timezone. By instance, this method tries to infer the timezone based on the locale (if available):
By instance: 
https://github.com/sonata-project/SonataIntlBundle/blob/153971d93f9f3fa1a2e8a4268eb77da812675ae6/src/Timezone/LocaleBasedTimezoneDetector.php#L48-L53
Given this example:
https://github.com/sonata-project/SonataIntlBundle/blob/153971d93f9f3fa1a2e8a4268eb77da812675ae6/src/Resources/views/CRUD/display_datetime.html.twig#L16-L22
we should replace that with something like this, in order to achieve a similar behavior with the extension provided by the official Twig repository:
```twig
{% set pattern = field_description.options.pattern|default(null) %}
{% set locale = field_description.options.locale|default(app.request.locale)|default(null) %}
{% set timezone = field_description.options.timezone|default(app.user.timezone)|default(null) %}
{% set dateType = field_description.options.dateType|default('medium') %}
{% set timeType = field_description.options.timeType|default('medium') %}

<time datetime="{{ value|date('c', 'UTC') }}" title="{{ value|date('c', 'UTC') }}">{{ value | localizeddate(dateType, timeType, locale, timezone, pattern) }}</time>
```
If the lost features doesn't worth, I think we can discuss about the deprecation.
