### ISSUE TITLE
RequestStackDetector does not have the default locale anymore.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataIntlBundle#487]
In Sonata-intl 2.11, I got an error message 
```
NumberFormatter::__construct() expects parameter 1 to be string, bool given
```
that I don't have with Sonata-Intl 2.10.

When I debug, I discovered that the `RequestStackDetector` receive `false` for the argument `$defaultLocale`.
With Sonata-Intl, instead of `false`, it correctly receive `'fr'`.

Could it be related to the migration of the config in https://github.com/sonata-project/SonataIntlBundle/pull/475/files cc @jordisala1991  @franmomu @Kocal ?

**Comment by Kocal** [comment]
Hi,

To me this should works as expected, the line https://github.com/sonata-project/SonataIntlBundle/blob/2.x/src/DependencyInjection/SonataIntlExtension.php#L90 is present.. but maybe `replaceArgument(1)` does not work anymore since the migration to PHP configuration?

What is the output of `dump($container->getDefinition('sonata.intl.locale_detector.request_stack'))`? 
Also what's inside `$config['locale']`?

Thanks

**Comment by VincentLanglet** [comment]
Thanks for your help @Kocal

The issue was this change
https://github.com/sonata-project/SonataIntlBundle/pull/477/files#diff-555a25b7dc4eb1f9537b50f88d18471062e8dd57e0bd46e0717899b097ca290e

`?:` was change to `??` but the default locale was `false`.  `null` should be preferred.
I opened https://github.com/sonata-project/SonataIntlBundle/pull/488
